apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: 'v2.livew.io/livewyer-test/demo-singleservice'
deploy:
  helm:
    releases:
    - name: demo-singleservice
      chartPath: charts/demo-singleservice
      skipBuildDependencies: true # Skip helm dep build
      setValueTemplates:
        imageName: '{{.DOCKER_REGISTRY}}/livewyer-test/demo-singleservice'