apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/livewyer-test/demo-singleservice:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/livewyer-test/demo-singleservice:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: demo-singleservice
        chartPath: charts/demo-singleservice
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/livewyer-test/demo-singleservice'
          image.tag: '{{.DIGEST_HEX}}'
